### PR TITLE
Install Numaflow CRDs as a depenency

### PR DESCRIPTION
**Pull request by xdevxy**
### Modifications

Since Numaplane is managing Numaflow, it is a dependency for sure. This PR includes the installation process with the Numaflow minimal CRDs.  If the destination environment already have Numaflow installed then this is just a noop. But it will be helpful for clusters that don't. 

### Verification
Verified in a local cluster

### CODE REVIEW

**Review by afugazzotto — APPROVED** [review]

**Comment by juliev0** [comment]
@xdevxy  Do we need this in our install.yaml? I just noticed that because this is here, and because we brought this file over to `numa-manifest-generator`, it is trying to install the numaflow CRDs there, which it should not, because that's part of the "numaflow" manifest installation

**Comment by xdevxy** [comment]
yeah, after we merged the addon, I think this is no longer needed internally, but this may still needed for open source users. Will this bring any issues if numaplane manifest try to install numaflow CRD again?

**Comment by juliev0** [comment]
> yeah, after we merged the addon, I think this is no longer needed internally, but this may still needed for open source users. Will this bring any issues if numaplane manifest try to install numaflow CRD again?

I definitely think it will create opportunity for error to have this installed by 2 things.

**Comment by juliev0** [comment]
I guess I do see why you wanted to include it here - the idea was that somebody could basically deploy numaplane and have what they need. But if we do keep it over here, then maybe we should have a separate manifest that gets created which doesn't include them? cc @whynowy

**Comment by xdevxy** [comment]
yeah, make sense to separate it out :)  do you mind creating an issue for it? Thanks!

**Pull request merged**
